---
- hosts: hinemosagents
  become: yes
  connection: local
  roles:
    - common
    - hinemosagent
  vars:
    MAJOR_VERSION: 6.2
    MINOR_VERSION: 2
    BUILD: 1
    OS_TYPE: el
    rpm_url: https://github.com/hinemos/hinemos/releases/download/v{{ MAJOR_VERSION }}.{{ MINOR_VERSION }}
    rpm_file: hinemos-{{ MAJOR_VERSION }}-agent-{{ MAJOR_VERSION }}.{{ MINOR_VERSION }}-{{ BUILD }}.{{ OS_TYPE }}.noarch.rpm
  environment:
    HINEMOS_MANAGER: 127.0.0.1
