---
- hosts: hinemosmanager
  become: yes
  connection: local
  roles:
    - hinemosmanager
  vars:
    git_url: https://github.com/hinemos/hinemos/releases/download
    MAJOR_VERSION: "6.2"
    MINOR_VERSION: "2"
    BUILD: "1"
    OS_TYPE: "el7"
