---
- hosts: hinemosweb
  become: yes
  connection: local
  roles:
    - common
    - locale
    - disableselinux
    - hinemosweb
  vars:
    BUILD: 1
    OS_TYPE: el8
    rpm_file: hinemos-{{ MAJOR_VERSION }}-web-{{ MAJOR_VERSION }}.{{ MINOR_VERSION }}-{{ BUILD }}.{{ OS_TYPE }}.x86_64.rpm
  environment:
    LANG: "{{ LOCALE }}"
