---
- hosts: hinemosweb
  become: yes
  connection: local
  roles:
    - common
    - disableselinux
    - hinemosweb
  vars:
    MAJOR_VERSION: 6.2
    MINOR_VERSION: 2
    BUILD: 1
    OS_TYPE: el7
    rpm_url: https://github.com/hinemos/hinemos/releases/download/v{{ MAJOR_VERSION }}.{{ MINOR_VERSION }}
    rpm_file: hinemos-{{ MAJOR_VERSION }}-web-{{ MAJOR_VERSION }}.{{ MINOR_VERSION }}-{{ BUILD }}.{{ OS_TYPE }}.x86_64.rpm
