---
- name: Install dependencies
  yum:
    state: latest
    name:
      - java-1.8.0-openjdk
      - vim-common
      - net-snmp
      - hostname
      - sudo

- name: Install package
  yum:
    name: "{{ rpm_url }}/{{ rpm_file }}"
    state: present
    disable_gpg_check: yes

- name: Start service
  service:
    name: hinemos_manager
    state: started
    enabled: yes

- name: Wait starting
  wait_for:
    port: 8080
