---
  - name: Install packages
    yum:
      state: latest
      name:
        - vlgothic-p-fonts

  - name: Disable SELinux
    selinux:
      state: disabled
    register: result

  - name: Reboot
    reboot:
    when: result.changed

  - name: Get Hinemos RPM File
    get_url:
      url: "{{ rpm_url }}/{{ rpm_file }}"
      dest: /tmp

  - name: Install Hinemos Web Client
    yum:
      name: /tmp/{{ rpm_file }}
      state: present

  - name: Start Hinemos Web Client Service
    service:
      name: hinemos_web
      state: started
      enabled: yes

  - name: Hinemos Web Client Listen Check (tcp 80)
    wait_for:
      port: 80
      delay: 10
