---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Install dependencies
  yum:
    state: latest
    name:
      - java-1.8.0-openjdk
      - vlgothic-p-fonts

- name: Install package
  yum:
    name: "{{ rpm_url }}/{{ rpm_file }}"
    state: present
    disable_gpg_check: yes

- name: Start service
  service:
    name: hinemos_web
    state: started
    enabled: yes

- name: Wait starting
  wait_for:
    port: 80
