---
- name: Install dependencies
  yum:
    state: latest
    name:
      - vlgothic-p-fonts

- name: Disable SELinux
  selinux:
    state: disabled
  register: result

- name: Reboot
  reboot:
  when: result.changed

- name: Get package
  get_url:
    url: "{{ rpm_url }}/{{ rpm_file }}"
    dest: /tmp

- name: Install package
  yum:
    name: /tmp/{{ rpm_file }}
    state: present

- name: Start service
  service:
    name: hinemos_web
    state: started
    enabled: yes

- name: Wait starting
  wait_for:
    port: 80
    delay: 3
