---
- name: Install dependencies
  yum:
    state: latest
    name:
      - java-1.8.0-openjdk
      - net-snmp
      - rsyslog
      - hostname
      - sudo

- name: Start rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Install package
  yum:
    name: "{{ rpm_url }}/{{ rpm_file }}"
    state: present
    disable_gpg_check: yes

- name: Start service
  service:
    name: hinemos_agent
    state: started
    enabled: yes
