---
- name: Get package
  get_url:
    url: "{{ rpm_url }}/{{ rpm_file }}"
    dest: /tmp

- name: Install package
  yum:
    name: /tmp/{{ rpm_file }}
    state: present

- name: Start service
  service:
    name: hinemos_agent
    state: started
    enabled: yes
